title:              CARLA Simulator
description:        Open-source simulator for autonomous driving research.
author:             CARLA Team
baseurl:            ""
url:                http://carla.org/
logo:               /img/logo/carla-black-m.png
default_background: /img/bg-post.jpg

# Social Profiles
cvc_page:          http://www.cvc.uab.es/
intel_page:        https://www.intel.com/
tri_page:          http://www.tri.global/
futurewei_page:    https://www.futurewei.com/
guardstrike_page:  https://www.guardstrike.com
nvidia_page:       https://www.nvidia.com

github_username:   carla-simulator
twitter_username:  carlasimulator
discord_invite:    8kqACuC
youtube_channel:   UC1llP9ekCwt8nEJzMJBQekg
forum:             carla-simulator/carla/discussions

twitter:
  username: carlasimulator

social:
  name: CARLA Simulator
  links:
    - https://github.com/carla-simulator/carla
    - https://twitter.com/carlasimulator
    - https://discord.gg/8kqACuC
    - https://www.youtube.com/channel/UC1llP9ekCwt8nEJzMJBQekg

# Build settings
markdown:          kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

jekyll-mentions:
  base_url: https://github.com

permalink:         pretty

paginate:          100
paginate_path:     "/posts/page:num/"

collections:
  team:
    output: true
    
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
